### ISSUE TITLE
Something that i am writing, would like to contribute ???

### ISSUE THREAD

**Issue by kunaldodiya** [zino-app/graphql-flutter#50]
Hey there,

I am going to write something awesome but need some contribution, so I thought to share it with you :)
What I am planning to build is a Dashboard for graphql-flutter client :)

The idea is to give user flexibility from writing code & using dashboard to create QUERY, MUTATION and SUBSCRIPTION without even touching a single file or writing a code.

Workflow is to generate a builder which will dynamically create json/yaml file and from that file we can generate .dart file which can be importable in flutter

Dashboard will have 4 sections :
1) SchemaBuilder
2) QueryBuilder
3) MutationBuilder
4) SubscriptionBuilder

inside `SchemaBuilder` user can specify schema identifier, fields and condition

for example 
```
  identifier:
       - GET_USERS_SCHHEMA
  fileds:
      - id
      - email
      - profile
           - name
           - mobile
  conditions:
     - user
         - where:
            - mobile ${mobile}
```

the above yaml generation is for our workflow, the user will have dashboard interface, with input box to fill. from that input a yaml reference like above will be generated and from that yaml a dart file in user `libs/dashy/schemas` folder will be generated.. yaml for our reference and dart for user, from that dart file he import

this will generate get_users_schema.dart in `libs/dashy/schemas`

```
String getUsersSchema = """
  query(\$mobile: String!) {
    user(where: { mobile: \$mobile }) {
      id
      email
      profile {
        name
        mobile
      }
    }
  }
  """
    .replaceAll('\n', ' ');
```
