### ISSUE TITLE
Running the client in AngularDart

### ISSUE THREAD

**Issue by Standaa** [zino-app/graphql-flutter#604]
**Describe the bug**
I am trying to get the library to work in AngularDart.
Merely importing the web package with `import 'package:graphql/client.dart';` crashes the app.

**To Reproduce**
1. Install package 3.0.0 in pubspec
2. Import in a component: `import 'package:graphql/client.dart';`
3. Serve app with `webdev serve`
4. See error `GET http://localhost:8080/main.dart.js net::ERR_ABORTED 404 (Not Found)`
The main.dart.js file is not loaded

**Expected behavior**
It should work in a browser environment & AngularDart

**Desktop (please complete the following information):**
 - OS: MacOs Catalina

**Observations**
The lib relies in several places on dart:io which does not exist in the browser.
Is the only solution a dedicated package for Angular, where all dart:io references would be removed ?

**Comment by micimize** [comment]
I've run [the `starwars` example on the `beta` branch](https://github.com/zino-app/graphql-flutter/tree/beta/examples/starwars) in web – try depending on `3.1.0-beta.4`

**Comment by binarypie** [comment]
@micimize This is still broken as far as I can tell when using dart2js for production. I've tried every single 3.* release on pub.dev and nothing has produced a running application locally with `webdev serve`.

Example: build.yaml
```
# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    sources:
      exclude:
      - css
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - test/**.browser_test.dart
        - web/**.dart
        options:
          compiler: dart2js
          dart2js_args:
          - --enable-diagnostic-colors
          - -O1
      build_web_compilers|dart_source_cleanup:
        release_options:
          enabled: false
```
