### ISSUE TITLE
had to click multiable times to get mutation data correctly

### ISSUE THREAD

**Issue by abdelrahmanelmarakby** [zino-app/graphql-flutter#949]
**I am trying to run mutation but for the first or second time result.data returns null as well as the context and the exception 
but when I run the mutation again it returns data correctly** 
 
here is my **VIEW** code :

``` 
Scaffold(
      appBar: AppBar(
        title: Text('LoginView'),
        centerTitle: true,
      ),
      body: Center(
        child: Mutation(
            options: MutationOptions(
                document: gql(Queries.LOGIN),
                fetchPolicy: FetchPolicy.networkOnly),
            builder: (runMutation, QueryResult? result) {
              return Column(
                children: [
                  TextFormField(
                    controller: controller.username,
                  ),
                  TextFormField(
                    controller: controller.password,
                  ),
                  TextButton(
                      onPressed: () async {
                        try {
                          runMutation(
                            {
                              "email": controller.username.text,
                              "password": controller.password.text,
                            },
                          );

                          print(result!.data);
                          token = result.data!["userLogin"]["token"];
                          print(token);
                          Get.toNamed(Routes.PROFILE, preventDuplicates: true);
                        } catch (e) {
                          print(e);
                        }
                      },
                      child: Text("GET TOKEN"))
                ],
              );
            }),
      ),
    );
```
 and this is my **query** : 
``` 
static final CREATE_PROPERTY = r"""mutation add_property($by: Int!, $name: String!,
   $purpose: String!, $propType: String!, $payMethod: String!, $available: Boolean!,
    $price: Float!, $area: Float!, $bedroom: Float!, $bathrooms: Float!, $image: Image) {
  createProperty(data: {createdBy: $by, propertyName: $name, purpose: $purpose,
   propType: $propType, payMethod: $payMethod, available: $available, price: $price, 
   area: $area, bedrooms: $bedroom, bathrooms: $bathrooms, verified: false,
   features: {elevator: false, attachment_building: false, servantRoom: false,
    has_furniture: false, carParking: false, carEntrance: false, hall: false,
     garden: false, kitchen: false},
    image: $image}) {
    id
    verified
    area
    available
    bathrooms
    bedrooms
    propertyName
    price
    createdBy {
      id
      name
      phone
      roles
    }
    propType
    payMethod
    image
  }
}
""";
```
**pubspec.yaml**

``` 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_easyloading: ^3.0.0
  get: 4.3.0
  graphql_flutter: ^5.0.0
  http: ^0.13.3
  infinite_scroll_pagination: ^3.1.0
  multi_image_picker2: ^5.0.2
  path: ^1.8.0
  responsive_framework: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: 1.0.1


```
