### ISSUE TITLE
Update to support newer connectivity_plus release

### ISSUE THREAD

**Issue by HaydenHMSD** [zino-app/graphql-flutter#983]
**Describe the issue**
I tried to add graphql-flutter to my project but running `pub get` failed with the following reason
```
Because graphql_flutter >=5.0.0 depends on connectivity_plus ^1.0.1 and your_project depends on connectivity_plus ^2.0.2, graphql_flutter >=5.0.0 is forbidden.
So, because your_project depends on graphql_flutter ^5.0.0, version solving failed.
pub get failed (1; So, because your_project depends on graphql_flutter ^5.0.0, version solving failed.)
```

**To Reproduce**
1. Add graphql_flutter to pubspec.yml
2. Run pub get
3. Observe pub error

**Expected behavior**
Add graphql_flutter with no conflict

**device / execution context**
Android Studio

**Comment by vincenzopalazzo** [comment]
Hi.

yesterday we have fixed this issue with the actual beta branch version, but only two days ago I begin the maintainer and I need to have all details on how to publish a new version of the package.

For now, you can solve the issue by link directly the repository in your `pubspec.yml`

```
  graphql_flutter:
    git:
      url: https://github.com/zino-app/graphql-flutter.git
      ref: beta
```
Let me know if this fixes the issue for the moment.

**Comment by diegodurli** [comment]
Hey @vincenzopalazzo 👋 

I've tried to get the git/package directly using the below pubspec but started seeing an error due to the relative path inside `graphql_flutter/pubspec` file.

```
  graphql_flutter:
    git:
      url: https://github.com/zino-app/graphql-flutter.git
      path: packages/graphql_flutter
```

```
Error on line 8, column 11: Invalid description in the "graphql_flutter" pubspec on the "graphql" dependency: "../graphql" is a relative path, but this isn't a local pubspec.
  ╷
8 │     path: ../graphql
  │           ^^^^^^^^^^
  ╵
pub get failed (65;   ╵)
exit code 65
```
